repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.14.5
    hooks:
      - id: typos
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
